export const COLORS = {
    main: '#fff',
    secondery: 'gray',
    third: '#fff',
    background: '#fafafa',

    blue: 'blue',
    gray: 'gray',
    lightGray: 'rgba(100,100,100,0.1)',
    lightGreen: 'rgba(100,255,0, 0.3)',
    black: 'black',
    text: '#000',
    text2: '#fff',
    text3: '#9F9F9F',
    icon: '#fff',
    tapIcon: '#fff',
    border: "#ccc",
    button: '#6F1E51',
    tapColor: '#FFC729',
    inActiveTap: '#FFF9DC',
    green: '#3B9A15',
    red: '#CA3314',
    facebook: '#3b5998',
    twitter: '#1DA1F2',
    youtube: '#FF0000',
    white: 'white',
    error: 'red',
    authActive: '#232F3E',
    blue: 'blue',
    authInActive: '#E2E6EF',
    lightBlue: '#F0F4FD',


}